version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: swift
    directory: /Pika.xcodeproj/project.xcworkspace/xcshareddata/swiftpm
    schedule:
      interval: weekly
